# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'GuardiasMIP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  pod 'EPCalendarPicker'
  pod 'Firebase/Core’
  pod 'Google-Mobile-Ads-SDK’, ‘~>7.9’

end
