# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GuardiasMIP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  pod 'EPCalendarPicker'
  use_frameworks!

  # Pods for GuardiasMIP

  target 'GuardiasMIPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuardiasMIPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
